# Generated by Django 5.1.6 on 2025-05-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firefighters',
            options={'ordering': ['rank', 'name'], 'verbose_name_plural': 'Firefighters'},
        ),
        migrations.AlterModelOptions(
            name='firetruck',
            options={'ordering': ['truck_number']},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ['name'], 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='firefighters',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fire.firestation'),
        ),
        migrations.AlterField(
            model_name='firetruck',
            name='capacity',
            field=models.DecimalField(decimal_places=2, help_text='Water capacity in liters', max_digits=10),
        ),
    ]
