# Generated by Django 5.1.6 on 2025-05-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_alter_firefighters_options_alter_firetruck_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firestation',
            options={'ordering': ['name']},
        ),
    ]
